# Generated by Django 2.2.5 on 2020-03-10 07:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catedra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Nucleo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.BigIntegerField()),
                ('direccion', models.TextField()),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudBien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('mensaje', models.TextField()),
                ('status', models.CharField(choices=[('L', 'Lista'), ('E', 'En espera')], default='E', max_length=1)),
                ('nucleo', models.ForeignKey(on_delete='cascade', to='principal.Nucleo')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudInstrumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('mensaje', models.TextField()),
                ('status', models.CharField(choices=[('L', 'Lista'), ('E', 'En espera')], default='E', max_length=1)),
                ('nucleo', models.ForeignKey(on_delete='cascade', to='principal.Nucleo')),
            ],
        ),
        migrations.CreateModel(
            name='TipoBien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TipoInstrumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudTipoInstrumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.IntegerField()),
                ('cantidad_aprobada', models.IntegerField()),
                ('instrumento', models.ForeignKey(on_delete='cascade', to='principal.TipoInstrumento')),
                ('solicitud', models.ForeignKey(on_delete='cascade', to='principal.SolicitudInstrumento')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudTipoBien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.IntegerField()),
                ('cantidad_aprobada', models.IntegerField()),
                ('bien', models.ForeignKey(on_delete='cascade', to='principal.TipoBien')),
                ('solicitud', models.ForeignKey(on_delete='cascade', to='principal.SolicitudBien')),
            ],
        ),
        migrations.CreateModel(
            name='Musico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.BigIntegerField()),
                ('direccion', models.TextField()),
                ('email', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('tipo', models.CharField(choices=[('A', 'Alumno'), ('P', 'Profesor')], max_length=1)),
                ('catedra', models.ForeignKey(on_delete='cascade', to='principal.Catedra')),
                ('nucleo', models.ForeignKey(on_delete='cascade', to='principal.Nucleo')),
            ],
        ),
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.BigIntegerField(default=None)),
                ('marca', models.CharField(default=None, max_length=50)),
                ('caracteristicas', models.TextField(default=None)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('DI', 'Disponible'), ('DE', 'Desincorporado')], default='DI', max_length=2)),
                ('nombre', models.ForeignKey(on_delete='cascade', to='principal.TipoInstrumento')),
                ('nucleo', models.ForeignKey(default=None, on_delete='cascade', to='principal.Nucleo')),
            ],
        ),
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.BigIntegerField()),
                ('marca', models.CharField(default=None, max_length=50)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('DI', 'Disponible'), ('DE', 'Desincorporado')], default='DI', max_length=2)),
                ('nombre', models.ForeignKey(on_delete='cascade', to='principal.TipoBien')),
                ('nucleo', models.ForeignKey(default=None, on_delete='cascade', to='principal.Nucleo')),
            ],
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrumento', models.ForeignKey(on_delete='cascade', to='principal.Instrumento')),
                ('musico', models.ForeignKey(on_delete='cascade', to='principal.Musico')),
            ],
        ),
        migrations.CreateModel(
            name='AlumnoRepresentante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musico', models.ForeignKey(on_delete='cascade', to='principal.Musico')),
                ('representante', models.ForeignKey(on_delete='cascade', to='principal.Representante')),
            ],
        ),
    ]
