# Generated by Django 2.2.5 on 2020-03-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_musico_fecha_ing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musico',
            name='fecha_ing',
            field=models.DateField(),
        ),
    ]
