# Generated by Django 2.2.5 on 2020-03-10 17:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_auto_20200310_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='fecha_fin',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='fecha_ini',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
