# Generated by Django 2.2.5 on 2020-03-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_galeria'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudbien',
            name='tipo',
            field=models.CharField(default='B', max_length=1),
        ),
        migrations.AddField(
            model_name='solicitudinstrumento',
            name='tipo',
            field=models.CharField(default='I', max_length=1),
        ),
    ]
