# Generated by Django 2.2.5 on 2020-03-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_auto_20200311_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudtipobien',
            name='cantidad_aprobada',
            field=models.IntegerField(default=0),
        ),
    ]
