# Generated by Django 2.2.5 on 2020-03-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_auto_20200322_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudtipoinstrumento',
            name='cantidad_aprobada',
            field=models.IntegerField(default=0),
        ),
    ]
