# Generated by Django 2.2.5 on 2020-04-17 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0010_coordinador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinador',
            name='cedula',
        ),
    ]
