# Generated by Django 2.2.5 on 2020-04-22 20:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0011_remove_coordinador_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudbien',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='InstrumentoDesincorporado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(default='I', max_length=1)),
                ('status', models.CharField(choices=[('A', 'Apobada'), ('E', 'En espera'), ('R', 'Rechazada')], default='E', max_length=1)),
                ('nombre', models.ForeignKey(on_delete='cascade', to='principal.Instrumento')),
            ],
        ),
        migrations.CreateModel(
            name='BienDesincorporado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(default='B', max_length=1)),
                ('status', models.CharField(choices=[('A', 'Apobada'), ('E', 'En espera'), ('R', 'Rechazada')], default='E', max_length=1)),
                ('nombre', models.ForeignKey(on_delete='cascade', to='principal.Bien')),
            ],
        ),
    ]
