# Generated by Django 2.2.5 on 2020-04-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0012_auto_20200422_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudbien',
            name='status',
            field=models.CharField(choices=[('L', 'Lista'), ('E', 'En espera'), ('A', 'Aceptada')], default='E', max_length=1),
        ),
        migrations.AlterField(
            model_name='solicitudinstrumento',
            name='status',
            field=models.CharField(choices=[('L', 'Lista'), ('E', 'En espera'), ('A', 'Aceptada')], default='E', max_length=1),
        ),
    ]
