# Generated by Django 2.2.5 on 2020-04-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0013_auto_20200423_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='caracteristicas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bien',
            name='nucleo',
            field=models.ForeignKey(on_delete='cascade', to='principal.Nucleo'),
        ),
    ]
