# Generated by Django 2.2.5 on 2020-04-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0014_auto_20200423_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
