# Generated by Django 2.2.5 on 2020-04-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0015_auto_20200424_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('imagen', models.ImageField(upload_to='')),
                ('asignacion', models.ForeignKey(on_delete='cascade', to='principal.Asignacion')),
            ],
        ),
    ]
