# Generated by Django 2.2.5 on 2020-04-25 20:14

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('principal', '0017_auto_20200424_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Voz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Partitura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tonalidad', models.CharField(choices=[('E', 'E'), ('C', 'C')], max_length=5)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('media', models.FileField(upload_to='partituras/')),
                ('autor', models.ForeignKey(on_delete='cascade', to='principal.Autor')),
                ('usuario', models.ForeignKey(on_delete='cascade', to=settings.AUTH_USER_MODEL)),
                ('voz', models.ForeignKey(on_delete='cascade', to='principal.Voz')),
            ],
        ),
    ]
