# Generated by Django 2.2.5 on 2020-05-23 17:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('principal', '0018_autor_partitura_voz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='perfiles/')),
                ('usuario', models.ForeignKey(on_delete='cascade', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartituraMusico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musico', models.ForeignKey(on_delete='cascade', to='principal.Musico')),
                ('partitura', models.ForeignKey(on_delete='cascade', to='principal.Partitura')),
            ],
        ),
    ]
