# Generated by Django 2.2.5 on 2020-06-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0020_auto_20200526_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(default='perfiles/profile.png', upload_to='perfiles/'),
        ),
    ]
