# Generated by Django 2.2.5 on 2020-06-06 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0022_perfil_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinador',
            name='foto',
            field=models.ImageField(default='perfiles/profile.png', upload_to='perfiles/'),
        ),
    ]
