# Generated by Django 2.2.5 on 2020-06-09 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0023_coordinador_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='musico',
            name='foto',
            field=models.ImageField(default='perfiles/profile.png', upload_to='perfiles/'),
        ),
    ]
