# Generated by Django 2.2.3 on 2020-06-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0024_musico_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='status',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
